In [2]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [3]:
preliminary_df = pd.read_csv('chm_jail_data.csv', na_values = ['nan', 'Unknown', 'Other'])
preliminary_df

/var/folders/rz/99x91dzn46xdnlv1swhwtc9r0000gn/T/ipykernel_14180/1251039999.py:1: DtypeWarning: Columns (18) have mixed types. Specify dtype option on import or set low_memory=False.
  preliminary_df = pd.read_csv('chm_jail_data.csv', na_values = ['nan', 'Unknown', 'Other'])

,booking_number,booking_date,booking_time,jacket_number,jacket_type,released_date,released_time,arrest_agency,age_at_arrest,age_at_release,...,crime,superhighlevel,finalanswercode,finalanswerdesc,custody_class,inmate_status,incarc_reason,booking_reason,release_reason_description,release_reason
0,201200000001,1/1/2012,0:19:14,22914,A,1/1/2012,1:57:29,Champaign Police Department,51.0,51.0,...,DRIVING UNDER THE INFLUENCE OF ALCOHOL,DUI,C69,Driving Under the Influence,NaN,NaN,Arrest - Without Warrant,Arrested Without Warrant,Credit Card Bond Posted,Bond Posted
1,201200000001,1/1/2012,0:19:14,22914,A,1/1/2012,1:57:29,Champaign Police Department,51.0,51.0,...,OTHER TRAFFIC OFFENSES,Traffic,C28,Traffic Offenses,NaN,NaN,Arrest - Without Warrant,Arrested Without Warrant,Credit Card Bond Posted,Bond Posted
2,201200000001,1/1/2012,0:19:14,22914,A,1/1/2012,1:57:29,Champaign Police Department,51.0,51.0,...,"RESISTING,OBSTRUCTING,OR DISARMING A POLICE OFC",Public Order,C31,Interfering w/Public Officers,NaN,NaN,Arrest - Without Warrant,Arrested Without Warrant,Credit Card Bond Posted,Bond Posted
3,201200000002,1/1/2012,1:44:45,1024225,A,1/2/2012,10:40:39,Champaign Police Department,32.0,32.0,...,DOMESTIC BATTERY,Violent,C05,Battery,NaN,NaN,Arrest - Without Warrant,Arrested Without Warrant,Credit Card Bond Posted,Bond Posted
4,201200000002,1/1/2012,1:44:45,1024225,A,1/2/2012,10:40:39,Champaign Police Department,32.0,32.0,...,AGGRAVATED BATTERY,Violent,C05,Battery,NaN,NaN,Arrest - Without Warrant,Arrested Without Warrant,Credit Card Bond Posted,Bond Posted
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
67918,201800002539,6/30/2018,12:36:48,1069755,A,6/30/2018,13:15:04,Champaign County Sherriff's Office,32.0,32.0,...,SUSPENDED OR REVOKED DRIVERS LICENSE,Traffic,C28,Traffic Offenses,NaN,NaN,FTA - Traffic Warrant,Failure to Appear,Cash Bond Posted,Bond Posted
67919,201800002540,6/30/2018,19:26:59,1000385,A,6/30/2018,21:15:00,Urbana Police Department,30.0,30.0,...,RETAIL THEFT,Property,C11,Theft,NaN,NaN,Arrest - Champaign County Warrant,Arrested on Warrant,Cash Bond Posted,Bond Posted
67920,201800002541,6/30/2018,21:05:36,990152,A,6/30/2018,22:30:55,Champaign Police Department,29.0,29.0,...,UNLAWFUL USE OF A WEAPON,Public Order,C18,Weapons Offenses,NaN,NaN,Arrest - Without Warrant,Arrested Without Warrant,Cash Bond Posted,Bond Posted
67921,201800002542,6/30/2018,21:28:09,34365,A,7/1/2018,11:20:30,Rantoul Police Department,46.0,46.0,...,DOMESTIC BATTERY,Violent,C05,Battery,NaN,NaN,Arrest - Without Warrant,Arrested Without Warrant,NaN,NaN
67922,201800002543,6/30/2018,22:39:25,1060848,A,7/2/2018,14:55:06,University of Illinois Police Department,58.0,58.0,...,SUSPENDED OR REVOKED DRIVERS LICENSE,Traffic,C28,Traffic Offenses,NaN,NaN,Arrest - Without Warrant,Arrested Without Warrant,NaN,NaN

In [4]:
preliminary_df['superhighlevel'].unique()

array(['DUI', 'Traffic', 'Public Order', 'Violent', nan, 'Drug',
       'Domestic Violence', 'Property', 'Sex'], dtype=object)

In [5]:
preliminary_df.sort_values(by=['jacket_number', 'booking_date'], inplace=True)



preliminary_df['repeat_offenses'] = preliminary_df.groupby('jacket_number')['booking_date'].transform('nunique') - 1

preliminary_df['repeat_offenses'].fillna(0, inplace=True)

preliminary_df

,booking_number,booking_date,booking_time,jacket_number,jacket_type,released_date,released_time,arrest_agency,age_at_arrest,age_at_release,...,superhighlevel,finalanswercode,finalanswerdesc,custody_class,inmate_status,incarc_reason,booking_reason,release_reason_description,release_reason,repeat_offenses
15114,201300001567,3/16/2013,20:34:12,6265,A,3/17/2013,11:20:44,Champaign Police Department,72.0,72.0,...,Property,C11,Theft,NaN,NaN,Arrest - Without Warrant,Arrested Without Warrant,NaN,NaN,0
35842,201500000271,1/20/2015,11:03:08,6565,A,1/20/2015,14:15:29,Champaign Police Department,71.0,71.0,...,NaN,NaN,Ordinance Violation,NaN,NaN,Arrest - City Warrant,"Arrested on Warrant -- !! break down later, FT...",NaN,NaN,4
44615,201500005482,11/18/2015,14:10:18,6565,A,11/25/2015,15:04:41,Urbana Police Department,72.0,72.0,...,NaN,NaN,Ordinance Violation,NaN,NaN,FTA - CITY WARRANT (OV),Failure to Appear,NaN,NaN,4
2361,201200001399,3/10/2012,18:33:01,6565,A,3/12/2012,10:51:29,University of Illinois Police Department,68.0,68.0,...,NaN,C86,Warrants & Summons,NaN,NaN,Arrest - City Warrant,"Arrested on Warrant -- !! break down later, FT...",NaN,NaN,4
2362,201200001399,3/10/2012,18:33:01,6565,A,3/12/2012,10:51:29,University of Illinois Police Department,68.0,68.0,...,NaN,NaN,Ordinance Violation,NaN,NaN,Arrest - City Warrant,"Arrested on Warrant -- !! break down later, FT...",NaN,NaN,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
67885,201800002518,6/29/2018,4:56:49,1069768,A,6/29/2018,14:50:33,Urbana Police Department,31.0,31.0,...,Violent,C05,Battery,NaN,NaN,Arrest - Without Warrant,Arrested Without Warrant,NaN,NaN,0
67886,201800002518,6/29/2018,4:56:49,1069768,A,6/29/2018,14:50:33,Urbana Police Department,31.0,31.0,...,Violent,C05,Battery,NaN,NaN,Arrest - Without Warrant,Arrested Without Warrant,NaN,NaN,0
67909,201800002532,6/30/2018,1:21:07,1069774,A,6/30/2018,2:39:41,Urbana Police Department,35.0,35.0,...,DUI,C69,Driving Under the Influence,NaN,NaN,Arrest - Without Warrant,Arrested Without Warrant,Credit Card Bond Posted,Bond Posted,0
67910,201800002532,6/30/2018,1:21:07,1069774,A,6/30/2018,2:39:41,Urbana Police Department,35.0,35.0,...,NaN,NaN,NaN,NaN,NaN,Arrest - Without Warrant,Arrested Without Warrant,Credit Card Bond Posted,Bond Posted,0
67911,201800002532,6/30/2018,1:21:07,1069774,A,6/30/2018,2:39:41,Urbana Police Department,35.0,35.0,...,Traffic,C28,Traffic Offenses,NaN,NaN,Arrest - Without Warrant,Arrested Without Warrant,Credit Card Bond Posted,Bond Posted,0

In [6]:
preliminary_df[preliminary_df.repeat_offenses > 0]

,booking_number,booking_date,booking_time,jacket_number,jacket_type,released_date,released_time,arrest_agency,age_at_arrest,age_at_release,...,superhighlevel,finalanswercode,finalanswerdesc,custody_class,inmate_status,incarc_reason,booking_reason,release_reason_description,release_reason,repeat_offenses
35842,201500000271,1/20/2015,11:03:08,6565,A,1/20/2015,14:15:29,Champaign Police Department,71.0,71.0,...,NaN,NaN,Ordinance Violation,NaN,NaN,Arrest - City Warrant,"Arrested on Warrant -- !! break down later, FT...",NaN,NaN,4
44615,201500005482,11/18/2015,14:10:18,6565,A,11/25/2015,15:04:41,Urbana Police Department,72.0,72.0,...,NaN,NaN,Ordinance Violation,NaN,NaN,FTA - CITY WARRANT (OV),Failure to Appear,NaN,NaN,4
2361,201200001399,3/10/2012,18:33:01,6565,A,3/12/2012,10:51:29,University of Illinois Police Department,68.0,68.0,...,NaN,C86,Warrants & Summons,NaN,NaN,Arrest - City Warrant,"Arrested on Warrant -- !! break down later, FT...",NaN,NaN,4
2362,201200001399,3/10/2012,18:33:01,6565,A,3/12/2012,10:51:29,University of Illinois Police Department,68.0,68.0,...,NaN,NaN,Ordinance Violation,NaN,NaN,Arrest - City Warrant,"Arrested on Warrant -- !! break down later, FT...",NaN,NaN,4
29746,201400003134,6/25/2014,14:41:07,6565,A,6/26/2014,7:39:54,Urbana Police Department,70.0,70.0,...,NaN,NaN,Ordinance Violation,NaN,NaN,FTA - CITY WARRANT (OV),Failure to Appear,CCSO Release on Recognizance,CCSO Release on Recognizance - NEW,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
67092,201800001999,5/25/2018,16:14:14,1069398,A,5/26/2018,11:38:05,University of Illinois Police Department,20.0,20.0,...,Public Order,C77,Trespassing,NaN,NaN,Arrest - Without Warrant,Arrested Without Warrant,NaN,NaN,1
67144,201800002029,5/27/2018,16:07:03,1069446,A,6/13/2018,11:04:20,Rantoul Police Department,55.0,55.0,...,Violent,C05,Battery,NaN,NaN,Arrest - Without Warrant,Arrested Without Warrant,NaN,NaN,1
67666,201800002377,6/19/2018,10:52:19,1069446,A,6/26/2018,16:04:46,Rantoul Police Department,55.0,55.0,...,NaN,C35,Violation of Crim Reg Laws,NaN,NaN,Arrest - Without Warrant,Arrested Without Warrant,NaN,NaN,1
67773,201800002438,6/23/2018,5:54:55,1069724,A,6/23/2018,13:37:24,Champaign County Sherriff's Office,24.0,24.0,...,Drug,C24,Controlled Substance Offenses,NaN,NaN,Arrest - Without Warrant,Arrested Without Warrant,Credit Card Bond Posted,Bond Posted,1
67844,201800002489,6/27/2018,13:59:44,1069724,A,6/27/2018,15:16:32,Champaign Police Department,24.0,24.0,...,Drug,C23,Methamphetamine Offenses,NaN,NaN,FTA - Criminal Warrant,Failure to Appear,Credit Card Bond Posted,Bond Posted,1

In [7]:
preliminary_df.groupby(by= ['jacket_number', 'booking_date']).agg('count').reset_index()

,jacket_number,booking_date,booking_number,booking_time,jacket_type,released_date,released_time,arrest_agency,age_at_arrest,age_at_release,...,superhighlevel,finalanswercode,finalanswerdesc,custody_class,inmate_status,incarc_reason,booking_reason,release_reason_description,release_reason,repeat_offenses
0,6265,3/16/2013,1,1,1,1,1,1,1,1,...,1,1,1,0,0,1,1,0,0,1
1,6565,1/20/2015,1,1,1,1,1,1,1,1,...,0,0,1,0,0,1,1,0,0,1
2,6565,11/18/2015,1,1,1,1,1,1,1,1,...,0,0,1,0,0,1,1,0,0,1
3,6565,3/10/2012,2,2,2,2,2,2,2,2,...,0,1,2,0,0,2,2,0,0,2
4,6565,6/25/2014,1,1,1,1,1,1,1,1,...,0,0,1,0,0,1,1,1,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
40556,1069761,6/28/2018,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,0,0,1
40557,1069763,6/28/2018,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,0,0,1
40558,1069766,6/28/2018,3,3,3,3,3,3,3,3,...,2,3,3,3,3,3,3,0,0,3
40559,1069768,6/29/2018,2,2,2,2,2,2,2,2,...,2,2,2,0,0,2,2,0,0,2
40560,1069774,6/30/2018,3,3,3,3,3,3,3,3,...,2,2,2,0,0,3,3,3,3,3

In [8]:
preliminary_df['employment_status'].isna().sum()

857

In [9]:
crime_mapping = {
    'DUI': 2,
    'Traffic': 0,
    'Public Order': 1,
    'Violent': 5,
    'Drug': 4,
    'Domestic Violence': 6,
    'Property': 3,
    'Sex': 7
}

In [10]:
preliminary_df['crime_level'] = preliminary_df['superhighlevel'].map(crime_mapping)
preliminary_df['crime_level']

15114    3.0
35842    NaN
44615    NaN
2361     NaN
2362     NaN
        ...
67885    5.0
67886    5.0
67909    2.0
67910    NaN
67911    0.0
Name: crime_level, Length: 67923, dtype: float64

In [11]:
preliminary_df['school'].unique()

array(['Urbana High School', 'Completed GED Program',
       'Attends non-local school', 'Graduated from high school', nan,
       'Centennial High School', 'Non-attender', 'Central High School',
       'Attends other local school',
       'GED program--enrolled in or starting soon',
       'Columbia Center High School', 'Rantoul Township High School',
       'Unity High School', 'Mahomet-Seymour High School',
       'St. Joseph-Ogden High School', 'Parkland Community College',
       'Heritage Junior High School', 'Urbana Adult Ed',
       'Unknown to minor', 'Fisher Junior-Senior High School',
       'Heritage Senior High School', 'Unity Junior High School',
       'READY High School', 'Urbana Middle School', 'Circle Academy',
       'Novac Academy', 'Yankee Ridge', 'St. Joseph Junior High School',
       'READY Middle School', 'Storefront School', 'The Pavilion School',
       'HS of Saint Thomas Moore', 'University Laboratory High School',
       'Judah Christian', 'Academic Academy', 'Gerber School at CCH',
       'Edison Middle School'], dtype=object)

In [12]:
#def mother(preliminary_df):

In [ ]:
categorical_cols = ['booking_date', 'released_date', 'arrest_agency', 'marital_status', 'employment_status', 'city', 'race', 'sex', 'STATE', 'citizenship', 'occupation', 'school', 'prisoner_type', 'crime_level', 'repeat_offenses']
num_cols = ['jacket_number', 'age_at_arrest', 'age_at_release', 'hours']

cat_dummies = pd.get_dummies(preliminary_df[categorical_cols], drop_first = True)
df = pd.concat([preliminary_df[num_cols], cat_dummies], axis = 1)

from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
df = pd.DataFrame(scaler.fit_transform(df), columns = df.columns)

from sklearn.impute import KNNImputer
imputer = KNNImputer(n_neighbors = 261)
df = pd.DataFrame(imputer.fit_transform(df),columns = df.columns)

In [ ]:
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer

imputer = IterativeImputer()
preliminary_df['crime_level'] = imputer.fit_transform(preliminary_df[['crime_level']])
preliminary_df['crime_level'].value_counts()

In [ ]:
employment_mapping = {
    'Unemployed': 0,
    'Retired': 1,
    'Laid Off': 2,
    'Employed - Part Time': 3,
    'Student': 4,
    'Self Employed': 5,
    'Employed - Full Time': 6,
}

In [ ]:
preliminary_df['employment_level'] = preliminary_df['employment_status'].map(employment_mapping)
preliminary_df['employment_level']

In [ ]:
imputer = IterativeImputer()
preliminary_df['employment_level'] = imputer.fit_transform(preliminary_df[['employment_level']])
preliminary_df['employment_level'].value_counts()

In [ ]:
df_filtered = preliminary_df[['booking_date', 'released_date', 'jacket_number', 'arrest_agency', 'age_at_arrest', 'age_at_release', 'hours', 'marital_status', 'employment_status', 'city', 'race', 'sex', 'STATE', 'citizenship', 'occupation', 'school', 'prisoner_type', 'crime_level', 'repeat_offenses']]
df_filtered

In [ ]:
df_dropNa = df_filtered.dropna()
df_dropNa

In [ ]:
df_filtered.isna().sum()

In [ ]:
df_filtered['offense_level'].unique()